In [2]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer , WordNetLemmatizer
from nltk.corpus import stopwords
import re
import pandas as pd

In [3]:
data = pd.read_csv("./tripadvisor_hotel_reviews.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  109 non-null    object
 1   Rating  109 non-null    int64
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

In [5]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [6]:
data["review_lower"] = data["Review"].str.lower()

In [7]:
data.head()

,Review,Rating,review_lower
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [8]:
en_stopwords = stopwords.words("english")

In [9]:
en_stopwords.remove("not")

In [10]:
data["review_no_stopwords"] = data["review_lower"].apply(lambda x : ' '.join([word for word in x.split() if word not in en_stopwords]))

In [11]:
data.head()

,Review,Rating,review_lower,review_no_stopwords
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [12]:
data["review_no_punct_no_stopword"] = data.apply(lambda x : re.sub(r"[*]" , "star" , x["review_no_stopwords"]), axis=1)

In [13]:
data.head()

,Review,Rating,review_lower,review_no_stopwords,review_no_punct_no_stopword
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [14]:
data["review_no_punct_no_stopword"] = data.apply(lambda x : re.sub(r"[^\w\s]" , "" , x["review_no_punct_no_stopword"]), axis=1)

In [15]:
data["tokenization"] = data.apply(lambda x : word_tokenize(x["review_no_punct_no_stopword"]) , axis=1)

In [16]:
data["tokenization"][0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'reviews',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillows',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bangs',
 'doors',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbors',
 'aveda',
 'bath',
 'products',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

In [17]:
ps = PorterStemmer()

In [18]:
data["stemmed"] = data.apply(lambda x : [ps.stem(word) for word in x["tokenization"]] , axis=1)

In [19]:
data["stemmed"]

0      [nice, hotel, expens, park, got, good, deal, s...
1      [ok, noth, special, charg, diamond, member, hi...
2      [nice, room, not, 4star, experi, hotel, monaco...
3      [uniqu, great, stay, wonder, time, hotel, mona...
4      [great, stay, great, stay, went, seahawk, game...
                             ...
104    [fairmont, hotel, singapor, splendid, stay, fa...
105    [great, hotel, stay, hotel, night, rout, perth...
106    [great, hotel, centr, stay, 5, night, room, ov...
107    [great, locat, great, valu, great, hotel, husb...
108    [love, hotel, great, locat, stay, vacat, tour,...
Name: stemmed, Length: 109, dtype: object

In [20]:
lemmatizer = WordNetLemmatizer()

In [21]:
data["lemmatized"] = data.apply(lambda x : [lemmatizer.lemmatize(word) for word in x["tokenization"]] , axis=1)

In [22]:
token_clean = sum(data["lemmatized"] , [])

In [23]:
unigram = (pd.Series(nltk.ngrams(token_clean, 1)).value_counts())
print(unigram)

(hotel,)           292
(room,)            275
(great,)           126
(not,)             122
(stay,)             95
                  ...
(175,)               1
(smackagainst,)      1
(2x,)                1
(80,)                1
(connected,)         1
Name: count, Length: 2589, dtype: int64

In [24]:
bigram = (pd.Series(nltk.ngrams(token_clean, 2)).value_counts())
print(bigram)

(great, location)     24
(space, needle)       21
(hotel, monaco)       16
(great, hotel)        12
(staff, friendly)     12
                      ..
(didnt, make)          1
(personnel, didnt)     1
(minute, stay)         1
(starting, minute)     1
(food, raffle)         1
Name: count, Length: 8263, dtype: int64